# Generated by Django 3.0.7 on 2020-06-09 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='place_images/', verbose_name='Image')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='places.Place')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
