# Generated by Django 3.0.7 on 2020-06-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-sort',), 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('title',), 'verbose_name_plural': 'Places'},
        ),
        migrations.AddField(
            model_name='image',
            name='sort',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
